Fail init command if project already has yoda initialized

diff --git a/yoda b/yoda
--- a/yoda
+++ b/yoda
@@ -45,6 +45,15 @@ custom_run() {
 
 case "$cmd" in
   init)
+    if [[ -e docker ]]; then
+      echo "Error while initializing Yoda. Folder 'docker' already exists."
+      if [[ -f docker/.yodarc ]]; then
+        source docker/.yodarc
+        echo "Initialized Yoda version: $YODA_VERSION"
+      fi
+      exit 1
+    fi
+
     project_name=${arg_name:-$(basename `pwd`)}
     username=$(git config --global user.name || echo 'Unknown maintainer')
     useremail=$(git config --global user.email || echo 'noreply@yoda.org')
